### ISSUE TITLE
No need to set CORS headers in mantil.go

### ISSUE THREAD

**Issue by ianic** [mantil-io/mantil#108]
We are letting HTTP API Gateway to [set CORS headers](https://github.com/mantil-io/mantil/blob/027dd27ad6c6a37e63e337ab5f85891d3b6d6b2b/node/terraform/modules/http-api/api.tf#L4).
And mantil.go is also setting CORS headers on [response](https://github.com/mantil-io/mantil.go/blob/845476e8b2dae9333158fab6a48c7779423841a9/caller.go#L108)
That will be removed by API Gateway in this configuration.

| If you configure CORS for an API, API Gateway ignores CORS headers returned from your backend integration.
[reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-cors.html)

**Comment by IvanVlasic** [comment]
Solved in [commit](https://github.com/mantil-io/mantil.go/commit/c7e97864a5295aa6d0b5d6f9dcb50d1f93d50522)
