### ISSUE TITLE
Raise code coverage in domain package

### ISSUE THREAD

**Issue by ianic** [mantil-io/mantil#112]
... so it looks nice in codecov.
Ref: https://atoz-technology.slack.com/archives/C024QHF6ZUN/p1644243755042109

**Comment by IvanVlasic** [comment]
Increased coverage of domain package up to 81.4%

```
PASS
ok  	github.com/mantil-io/mantil/domain	0.159s
ok  	github.com/mantil-io/mantil/domain	0.128s	coverage: 81.4% of statements
```

There might be few more things that make sense to test but I don't there's much to it.
