### ISSUE TITLE
mantil logs doesn't properly show logs of multiple parallel lambda executions

### ISSUE THREAD

**Issue by IvanVlasic** [mantil-io/mantil#16]
In case when there are multiple parallel executions of specific lambda logs command doesn't display all of the logs, but only part of them.

For example, creating lambda with following code:
```
func (p *Ping) Countdown(ctx context.Context, name string) {
	for i := 0; i < 10; i++ {
		fmt.Printf("%s says %d\n", name, i)
		time.Sleep(1 * time.Second)
	}
}
```
 and then executing it twice at the same time shows following logs:

![image](https://user-images.githubusercontent.com/10476262/131516478-0a916157-c264-4b36-b043-2d9c65aea674.png)

Actual logs are this:
![image](https://user-images.githubusercontent.com/10476262/131516536-6873d55c-28fb-48ec-ac78-6da2f15077de.png)

**Comment by ianic** [comment]
Noop right now.
